#!/bin/bash

#rm -f hopfield_par
for i in $(seq 5.6 0.1 8.4)
do
  if [ -e   "lat"$i"/gyo/gyo2.out" ]; then 
    Sb=$(head -n1 "lat"$i"/gyo/gyo2.out" | awk '{print $3}')
    H=$(tail -n1 "lat"$i"/gyo/gyo2.out" | awk '{print $3}')
  echo "$i  $Sb  $H " >> hopfield_par
  fi
done  

cat > eta_plot.gnu << EOF
set term eps
set output "sbh3_eta.eps"

set title "SbH_3 Hopfield Parameter, {/Symbol h}"
set ylabel "{/Symbol h}"
set xlabel "a (A)"
#set yrange[0.5:2.5]
plot "hopfield_par" u 1:2 w p pt 5 ps 0.65 t "{/Symbol h}_{Sb}",\
     "hopfield_par" u 1:(\$3*3) w p pt 3 ps 0.65 t "{/Symbol h}_H"


EOF

gnuplot eta_plot.gnu 
