#!/bin/bash
path='../'
for i in $(seq 54 2 74)
do
#	if [  -e $path/lat$i/gyo  ]; then
#		mkdir gyo-$i
#		cp $path/lat$i/dos/* gyo-$i/.
#		cp $path/lat$i/POT gyo-$i/.
#	        cp $path/lat$i/gyo/* gyo-$i/.
		cp gyo/* gyo-$i/.
#	fi
done
