#!/bin/bash


l=0
                  
declare -a ub=("2" "1.9" "1.8" "1.7" "1.6" "1.5") 
declare -a lb=("-2" "-1.9" "-1.8" "-1.7" "-1.6" "-1.5") 

for i in $(seq 5.8  0.1  6.3)
do
	cd gyo-$i/
	sed -i -e 's/at EF/at 0.0/g' dosplot.gnu
	sed -i -e 's/from EF/from 0.0/g' dosplot.gnu
	sed -i -e 's/to EF/to 0.0/g' dosplot.gnu
	sed -i "13 c\set xrange[${lb[l]}:${ub[l]}]" dosplot.gnu
	gnuplot dosplot.gnu
	cd ../

#	echo "$i [${lb[l]}:${ub[l]}]" 
    l=$(( $l + 1 ))
done
