#!/bin/bash

el="I"
rm extracted-h3$el.1785.txt
title=( "l" "SIN"  "DOS-PRODUCT" "ETA" "rs" "ef"  "nef" ) 
n=2
for i in ${!title[@]}  
do 
  col=${title[$i]}
  printf "\ncol=$col\n" >> extracted-h3$el.1785.txt
  printf "a \t $el-l=0 $el-l=1 $el-l=2 H-l=0 \n" >> extracted-h3$el.1785.txt
  echo "getting $col ..."

  for lat in $(seq 6.8 0.1 7.4 )
  do
	  if [ -e "gyo-$lat" ]; then
		
		  path="gyo-$lat"
		  printf "$lat \t" >> extracted-h3$el.1785.txt
		  awk -v x=$n '{print $x }' $path/fort.25 | head -n 4 | paste -s >> extracted-h3$el.1785.txt
          fi
  done
 

  n=$(( $n + 1 ))

done


